environment: prod
namespace: parasol-insurance-prod

image:
  tag: "1.0"

replicas: 2

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 512Gi

database:
  user: parasol
  password: parasol
  name: parasol

hpa:
  minReplicas: 2
  maxReplicas: 4
  cpuTargetPercent: 10
